-- ACL Expert Edition V2 — Phase 2.5 Competition Engine
-- Run after Phase 2.4. Safe to run more than once.
create extension if not exists pgcrypto;

create table if not exists public.competitions (
 id uuid primary key default gen_random_uuid(),
 module_id text not null references public.modules(id) on delete cascade,
 quiz_id uuid not null references public.quizzes(id) on delete cascade,
 slug text not null unique,
 title text not null,
 description text,
 opens_at timestamptz not null,
 closes_at timestamptz not null,
 duration_seconds integer not null default 1200 check(duration_seconds between 30 and 21600),
 attempts_allowed integer not null default 1 check(attempts_allowed between 1 and 20),
 confidence_scoring boolean not null default true,
 randomize_questions boolean not null default true,
 randomize_options boolean not null default true,
 leaderboard_visible boolean not null default true,
 anti_cheat_enabled boolean not null default true,
 warnings_allowed integer not null default 2 check(warnings_allowed between 0 and 10),
 status text not null default 'draft' check(status in ('draft','published','archived')),
 created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 check(closes_at > opens_at)
);

create table if not exists public.competition_attempts (
 id uuid primary key default gen_random_uuid(),
 competition_id uuid not null references public.competitions(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 started_at timestamptz not null default now(),
 submitted_at timestamptz,
 expires_at timestamptz not null,
 status text not null default 'in_progress' check(status in ('in_progress','submitted','terminated','expired')),
 score numeric not null default 0,
 correct_count integer not null default 0,
 answered_count integer not null default 0,
 accuracy numeric not null default 0,
 duration_seconds integer,
 warning_count integer not null default 0,
 created_at timestamptz not null default now()
);
create unique index if not exists competition_attempt_one_active_idx on public.competition_attempts(competition_id,user_id,id);
create index if not exists competition_attempt_rank_idx on public.competition_attempts(competition_id,status,score desc,accuracy desc,duration_seconds asc,submitted_at asc);

create table if not exists public.competition_answers (
 id uuid primary key default gen_random_uuid(),
 attempt_id uuid not null references public.competition_attempts(id) on delete cascade,
 question_id uuid not null references public.questions(id) on delete cascade,
 selected_option_ids uuid[] not null default '{}',
 confidence text check(confidence in ('low','high')),
 is_correct boolean,
 points_awarded numeric,
 answered_at timestamptz default now(),
 unique(attempt_id,question_id)
);

create table if not exists public.competition_events (
 id bigint generated by default as identity primary key,
 attempt_id uuid not null references public.competition_attempts(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 event_type text not null,
 details jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);

create or replace function public.acl_touch_competition() returns trigger language plpgsql as $$
begin new.updated_at=now(); new.slug=trim(both '-' from lower(regexp_replace(trim(new.slug),'[^a-zA-Z0-9]+','-','g'))); return new; end $$;
drop trigger if exists acl_touch_competition_trigger on public.competitions;
create trigger acl_touch_competition_trigger before insert or update on public.competitions for each row execute function public.acl_touch_competition();

alter table public.competitions enable row level security;
alter table public.competition_attempts enable row level security;
alter table public.competition_answers enable row level security;
alter table public.competition_events enable row level security;

drop policy if exists "Admins manage competitions" on public.competitions;
drop policy if exists "Users read published competitions" on public.competitions;
create policy "Admins manage competitions" on public.competitions for all to authenticated using(public.acl_is_admin()) with check(public.acl_is_admin());
create policy "Users read published competitions" on public.competitions for select to authenticated using(status='published' and public.acl_is_active_user());

drop policy if exists "Users own competition attempts" on public.competition_attempts;
drop policy if exists "Admins read all competition attempts" on public.competition_attempts;
create policy "Users own competition attempts" on public.competition_attempts for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "Admins read all competition attempts" on public.competition_attempts for select to authenticated using(public.acl_is_admin());

drop policy if exists "Users own competition answers" on public.competition_answers;
drop policy if exists "Admins read all competition answers" on public.competition_answers;
create policy "Users own competition answers" on public.competition_answers for all to authenticated using(exists(select 1 from public.competition_attempts a where a.id=attempt_id and a.user_id=auth.uid())) with check(exists(select 1 from public.competition_attempts a where a.id=attempt_id and a.user_id=auth.uid()));
create policy "Admins read all competition answers" on public.competition_answers for select to authenticated using(public.acl_is_admin());

drop policy if exists "Users add own competition events" on public.competition_events;
drop policy if exists "Admins read competition events" on public.competition_events;
create policy "Users add own competition events" on public.competition_events for insert to authenticated with check(user_id=auth.uid() and exists(select 1 from public.competition_attempts a where a.id=attempt_id and a.user_id=auth.uid()));
create policy "Admins read competition events" on public.competition_events for select to authenticated using(public.acl_is_admin());

grant select,insert,update,delete on public.competitions to authenticated;
grant select,insert,update on public.competition_attempts to authenticated;
grant select,insert,update on public.competition_answers to authenticated;
grant select,insert on public.competition_events to authenticated;

-- Public leaderboard without answer data.
create or replace function public.acl_competition_leaderboard(p_competition uuid)
returns table(rank bigint,user_id uuid,display_name text,position text,score numeric,accuracy numeric,duration_seconds integer,submitted_at timestamptz)
language sql security definer set search_path=public as $$
 select row_number() over(order by a.score desc,a.accuracy desc,a.duration_seconds asc,a.submitted_at asc),a.user_id,
 coalesce(p.full_name,p.username,'Participant'),p.position,a.score,a.accuracy,a.duration_seconds,a.submitted_at
 from competition_attempts a left join profiles p on p.id=a.user_id
 join competitions c on c.id=a.competition_id
 where a.competition_id=p_competition and a.status='submitted' and c.leaderboard_visible=true
 order by a.score desc,a.accuracy desc,a.duration_seconds asc,a.submitted_at asc;
$$;
grant execute on function public.acl_competition_leaderboard(uuid) to authenticated;
