/* ACL service worker v7.2.0 — network-first app shell */
const VERSION='acl-v7.2-20260820-1824';
const CACHE_NAME=VERSION;
const BASE='/Cardiology/';
self.addEventListener('install',event=>{self.skipWaiting();event.waitUntil(Promise.resolve());});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)));await self.clients.claim();const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const client of clients)client.postMessage({type:'ACL_SERVICE_WORKER_ACTIVATED',version:VERSION,cacheName:CACHE_NAME});})());});
function isNavigation(request){return request.mode==='navigate'||(request.headers.get('accept')||'').includes('text/html');}
function isAppCode(url){return /\.(?:js|css|json|webmanifest)$/i.test(url.pathname);}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin||!url.pathname.startsWith(BASE))return;event.respondWith((async()=>{try{const fresh=await fetch(request,{cache:(isNavigation(request)||isAppCode(url))?'no-store':'default'});if(fresh&&fresh.ok&&!isNavigation(request)){const cache=await caches.open(CACHE_NAME);cache.put(request,fresh.clone()).catch(()=>{});}return fresh;}catch(error){const cached=await caches.match(request,{ignoreSearch:false});if(cached)return cached;if(isNavigation(request))return new Response('ACL is temporarily offline. Please reconnect and reload.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});throw error;}})());});
self.addEventListener('message',event=>{const data=event.data||{};if(data.type==='SKIP_WAITING')self.skipWaiting();if(data.type==='CLEAR_ACL_CACHE')event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)));const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const client of clients)client.postMessage({type:'ACL_CACHE_CLEARED',cacheName:CACHE_NAME});})());});